# Query: ZON01
# Question: ¿Cuáles son las zonas reguladas?

# --- Query 1 ---
PREFIX edintzone: <https://edint.es/def/zona-regulatoria#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?zona
WHERE {
    ?zona rdf:type edintzone:RegulatedZone .
}

# --- Query 2 ---
PREFIX edintzone: <https://edint.es/def/zona-regulatoria#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?zona
WHERE {
    ?zona rdf:type edintzone:RegulatedZone ;
          edintzone:hasRegulatedZoneType ?tipo .
}
ORDER BY ?zona

