# Query: ZON08
# Question: ¿Cuáles son las zonas de interés económico y su referencia legal?

# --- Query 1 ---
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX edintkos-rztype: <https://edint.es/kos/RegulatedZoneType/>
PREFIX edintzone: <http://vocab.linkeddata.es/datosabiertos/def/common/zone#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?zona ?tipoZona ?refLegal
WHERE {
    ?zona rdf:type edintzone:RegulatedZone ;
          edintzone:hasRegulatedZoneType ?tipoZona .
    ?tipoZona skos:broader* edintkos-rztype:EconomicInterestZone .
    OPTIONAL { ?zona edintzone:legalReference ?refLegal . }
}
ORDER BY ?tipoZona ?zona

