# Query: ZON06
# Question: ¿Cuántas zonas reguladas hay por municipio?

# --- Query 1 ---
PREFIX edintzone: <https://edint.es/def/zona-regulatoria#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?municipio ?tipoZona (COUNT(?zona) AS ?numZonas)
WHERE {
    ?zona rdf:type edintzone:RegulatedZone ;
          edintzone:hasRegulatedZoneType ?tipoZona .
    ?zona edintzone:locatedIn ?municipio .
}
GROUP BY ?municipio ?tipoZona
ORDER BY ?municipio ?tipoZona

